spring.application.name=control-plane

spring.datasource.url=jdbc:mysql://localhost:3306/goldanalyze?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
spring.datasource.username=ganqy
spring.datasource.password=9958
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
